__author__ = "Richard Mwewa"
__about__ = "https://rly0nheart.github.io"
__version__ = "0.15.0"
__description__ = f"**Tor2Tor** - by [{__author__}]({__about__})"
__epilog__ = "**Tor2Tor** scrapes a given onion link and captures screenshots of all links available on it."
